FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . .

ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_API_CLIENT_KEY
ARG VITE_BASE_URL_API_CLIENT
ARG VITE_GOOGLE_MAPS_COORDINATES_URL

ENV VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
ENV VITE_API_CLIENT_KEY=${VITE_API_CLIENT_KEY}
ENV VITE_BASE_URL_API_CLIENT=${VITE_BASE_URL_API_CLIENT}
ENV VITE_GOOGLE_MAPS_COORDINATES_URL=${VITE_GOOGLE_MAPS_COORDINATES_URL}

RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
